/**
 * Everything the MCP tools say, rendered twice: `structuredContent` for code and markdown text for
 * the model reading it. Private source text is stripped here as a second line of defence; lib/rag
 * already returns `snippet: null` for private sources.
 */
import { RESUME, type ResumeData } from '@/content/resume'
import { TOPICS, topicLabel } from '@/content/topics'
import type { Answer, CitationSource, FitAssessment, FitDimension, TopicSummary } from '@/lib/rag/types'
import type { McpSource, McpTopic } from '@/lib/mcp/schemas'

export const DEFAULT_ORIGIN = 'https://curlycloud.dev'

const PRIVATE_KINDS = new Set(['interview', 'note', 'correction'])

export const CLONE_NOTICE = `AI-generated by Raj's clone from his resume and his own interview answers. Confirm anything important with Raj at ${RESUME.email}.`

function isPublic(s: CitationSource): boolean {
  return s.visibility === 'public' && !PRIVATE_KINDS.has(s.kind)
}

/** The only shape a citation leaves the server in. Private sources keep their label, nothing else. */
export function toMcpSource(s: CitationSource, cited: Set<number>, origin: string): McpSource {
  const pub = isPublic(s)
  return {
    n: s.n,
    id: s.id,
    kind: s.kind,
    visibility: pub ? 'public' : 'private',
    title: s.title,
    topic: s.topic ?? null,
    section: pub ? topicLabel(s.topic) : null,
    snippet: pub ? (s.snippet ?? null) : null,
    url: pub && s.anchor ? `${origin}/#${s.anchor}` : null,
    cited: cited.has(s.n),
  }
}

export function sourceLine(s: McpSource): string {
  const where = `${s.kind}/${s.topic ?? 'general'}`
  const detail =
    s.visibility === 'public'
      ? ` (resume section: ${s.section ?? 'General'}${s.url ? `, ${s.url}` : ''})`
      : ' (private: Raj’s own words, label only)'
  return `[${s.n}] ${s.title} — ${where}${detail}${s.cited ? ' · cited' : ''}`
}

function sourcesBlock(sources: McpSource[]): string[] {
  if (sources.length === 0) return ['Sources: none. The clone found nothing relevant in its knowledge base.']
  return ['Sources:', ...sources.map(sourceLine)]
}

// ── ask_raj ──────────────────────────────────────────────────────────────────

export interface AskStructured {
  answer: string
  sources: McpSource[]
  cited: number[]
  guarded: boolean
  provider: Answer['provider']
  model: string
}

export function askResult(a: Answer, origin: string): { text: string; structured: AskStructured } {
  const cited = new Set(a.cited)
  const sources = a.sources.map((s) => toMcpSource(s, cited, origin))
  const lines = [a.text.trim()]
  if (a.guarded) lines.push('', '(A safety guard cut this answer short.)')
  lines.push('', ...sourcesBlock(sources), '', `_${CLONE_NOTICE}_`)
  return {
    text: lines.join('\n'),
    structured: { answer: a.text, sources, cited: a.cited, guarded: a.guarded, provider: a.provider, model: a.model },
  }
}

// ── assess_fit ───────────────────────────────────────────────────────────────

const VERDICTS = ['strong', 'promising', 'mixed', 'weak'] as const

function score(n: unknown): number {
  const v = Number(n)
  return Number.isFinite(v) ? Math.min(5, Math.max(1, v)) : 1
}

function strings(xs: unknown): string[] {
  return Array.isArray(xs) ? xs.filter((x): x is string => typeof x === 'string' && x.trim() !== '') : []
}

function ints(xs: unknown): number[] {
  return Array.isArray(xs) ? xs.filter((x): x is number => Number.isInteger(x)) : []
}

function dimension(d: FitDimension | undefined): FitDimension {
  return {
    score: score(d?.score),
    summary: String(d?.summary ?? ''),
    strengths: strings(d?.strengths),
    gaps: strings(d?.gaps),
    evidence: ints(d?.evidence),
  }
}

export interface FitStructured {
  roleTitle: string
  company: string | null
  overall: { score: number; verdict: FitAssessment['overall']['verdict']; summary: string }
  technical: FitDimension
  culture: FitDimension
  unknowns: string[]
  questionsForRaj: string[]
  sources: McpSource[]
  provider: FitAssessment['provider']
  model: string
}

/** Clamp and fill whatever the model produced so it always matches the output schema. */
export function normalizeFit(f: FitAssessment, origin: string): FitStructured {
  const technical = dimension(f.technical)
  const culture = dimension(f.culture)
  const cited = new Set([...technical.evidence, ...culture.evidence])
  const verdict = VERDICTS.includes(f.overall?.verdict) ? f.overall.verdict : 'mixed'
  return {
    roleTitle: f.roleTitle,
    company: f.company ?? null,
    overall: { score: score(f.overall?.score), verdict, summary: String(f.overall?.summary ?? '') },
    technical,
    culture,
    unknowns: strings(f.unknowns),
    questionsForRaj: strings(f.questionsForRaj),
    sources: (f.sources ?? []).map((s) => toMcpSource(s, cited, origin)),
    provider: f.provider,
    model: f.model,
  }
}

function bullets(title: string, items: string[]): string[] {
  return items.length ? [`${title}:`, ...items.map((i) => `- ${i}`)] : [`${title}: none noted.`]
}

function dimensionBlock(name: string, d: FitDimension): string[] {
  const evidence = d.evidence.length ? d.evidence.map((n) => `[${n}]`).join(', ') : 'none cited'
  return [
    `### ${name}: ${d.score}/5`,
    d.summary,
    '',
    ...bullets('Strengths', d.strengths),
    ...bullets('Gaps', d.gaps),
    `Evidence: ${evidence}`,
    '',
  ]
}

export function fitMarkdown(f: FitStructured): string {
  const role = f.company ? `${f.roleTitle} at ${f.company}` : f.roleTitle
  return [
    `## Fit assessment: ${role}`,
    '',
    `**Overall: ${f.overall.verdict} (${f.overall.score}/5).** ${f.overall.summary}`,
    '',
    ...dimensionBlock('Technical fit', f.technical),
    ...dimensionBlock('Culture fit', f.culture),
    '### Unknowns (no evidence either way; ask Raj)',
    ...(f.unknowns.length ? f.unknowns.map((u) => `- ${u}`) : ['- None noted.']),
    '',
    '### Questions for Raj',
    ...(f.questionsForRaj.length ? f.questionsForRaj.map((q) => `- ${q}`) : ['- None noted.']),
    '',
    ...sourcesBlock(f.sources),
    '',
    `_${CLONE_NOTICE}_`,
  ].join('\n')
}

// ── Topics ───────────────────────────────────────────────────────────────────

const BLURBS: Record<string, string> = Object.fromEntries(TOPICS.map((t) => [t.id, t.blurb]))

export function liveTopics(summaries: TopicSummary[]): McpTopic[] {
  return summaries.map((t) => ({
    topic: t.topic,
    label: t.label || topicLabel(t.topic),
    blurb: BLURBS[t.topic] ?? null,
    count: Number.isFinite(t.count) ? Math.max(0, Math.round(t.count)) : null,
  }))
}

export function staticTopics(): McpTopic[] {
  return TOPICS.map((t) => ({ topic: t.id, label: t.label, blurb: t.blurb, count: null }))
}

export const TOPICS_NOTE =
  'Questions that work well are specific and about experience: how Raj approached a project, a trade-off he made, what he would do differently, how he evaluates LLM systems, how he works with a team, what he wants next. The clone answers only from its sources and says so when they do not cover something; treat that as an open question for Raj, not a negative signal.'

export function topicsMarkdown(topics: McpTopic[], source: 'live' | 'static'): string {
  const header =
    source === 'live'
      ? 'Topics the clone has knowledge about (source counts from its knowledge base):'
      : 'Topics the clone is built to cover (live coverage unavailable right now, so counts are unknown):'
  const lines = topics.map((t) => `- **${t.label}** (\`${t.topic}\`${t.count != null ? `, ${t.count} sources` : ''})${t.blurb ? `: ${t.blurb}` : ''}`)
  return [header, '', ...lines, '', TOPICS_NOTE].join('\n')
}

// ── Profile ──────────────────────────────────────────────────────────────────

export function howToReach(data: ResumeData = RESUME): string {
  return `Email ${data.email} (best for anything role-related: mention the company and role). LinkedIn: ${
    data.links.find((l) => l.label === 'LinkedIn')?.href ?? 'see links'
  }. For a higher-limit MCP API key for your company's agent, email the same address.`
}

export function profileStructured(topics: McpTopic[], topicsSource: 'live' | 'static', data: ResumeData = RESUME) {
  const current = data.experience.find((r) => r.end === null) ?? data.experience[0] ?? null
  return {
    name: data.name,
    role: data.role,
    headline: data.headline,
    pitch: data.pitch,
    location: data.location,
    email: data.email,
    links: data.links.map((l) => ({ label: l.label, href: l.href })),
    summary: [...data.summary],
    currentRole: current ? { company: current.company, role: current.role, period: current.period } : null,
    skills: data.skills.map((g) => ({ id: g.id, label: g.label, items: g.items.map((i) => i.label) })),
    topics,
    topicsSource,
    howToReach: howToReach(data),
  }
}

export function profileMarkdown(p: ReturnType<typeof profileStructured>): string {
  return [
    `# ${p.name}`,
    `**${p.role}**${p.currentRole ? ` at ${p.currentRole.company} (${p.currentRole.period})` : ''}. ${p.headline}`,
    '',
    p.pitch,
    '',
    `Location: ${p.location} · Email: ${p.email}`,
    `Links: ${p.links.map((l) => `${l.label} ${l.href}`).join(' · ')}`,
    '',
    '## Summary',
    ...p.summary.map((s) => `- ${s}`),
    '',
    '## Skills',
    ...p.skills.map((g) => `- **${g.label}:** ${g.items.join(', ')}`),
    '',
    '## What you can ask the clone about',
    ...p.topics.map((t) => `- ${t.label}${t.count != null ? ` (${t.count})` : ''}${t.blurb ? `: ${t.blurb}` : ''}`),
    '',
    '## How to reach Raj',
    p.howToReach,
    '',
    'Next: get_resume for the full resume, assess_fit with a job description, ask_raj for follow-ups.',
  ].join('\n')
}
