import type { Question } from './types'

export const CAREER: Question[] = [
  {
    id: 'career-001',
    topic: 'career',
    type: 'rapid',
    depth: 1,
    prompt: 'Describe your dream job title in five words or fewer.',
    hint: 'It does not have to exist yet.',
    followUps: ['Does anyone have that title today?', 'What would you actually do in your first week?'],
    why: 'The shorthand for his ambition, in his own words.',
  },
  {
    id: 'career-002',
    topic: 'career',
    type: 'open',
    depth: 2,
    prompt:
      'Out of everything you could specialise in, why AI engineering, and why now rather than two years ago or two years from now?',
    hint: 'What about this particular moment pulls you in?',
    followUps: [
      'What part of AI engineering do you find genuinely boring?',
      'What would make you walk away from AI and build something else entirely?',
    ],
    why: 'His authentic reason for choosing AI engineering, beyond it being the hot field.',
  },
  {
    id: 'career-003',
    topic: 'career',
    type: 'this-or-that',
    depth: 1,
    prompt: 'Which stage of a company gets the best out of you?',
    options: ['Finding product-market fit', 'Scaling something that works'],
    hint: 'Pinhous and Create Club on one side, Eddy on the other.',
    followUps: [
      'What is the most useful thing you do at the stage you did not pick?',
      'Which stage are you worst at, honestly?',
    ],
    why: 'The company stage he thrives in, which the clone uses when assessing fit.',
  },
  {
    id: 'career-004',
    topic: 'career',
    type: 'open',
    depth: 3,
    prompt: "It's 2030. What are you working on, who are you working with, and what does a Tuesday look like?",
    hint: 'Be concrete: the problem, the team size, the city, the kind of room you are sitting in.',
    followUps: [
      'What has to happen in the next 12 months for that to be on track?',
      'Is there a founder in that picture?',
      'What is conspicuously missing from it?',
    ],
    why: 'His three-to-five-year vision, including whether he sees himself founding again.',
  },
  {
    id: 'career-005',
    topic: 'career',
    type: 'this-or-that',
    depth: 2,
    prompt: "You've led a team of 12 at Pinhous and a remote team of 3 at Duit. For the next five years, which path?",
    options: ['Hands-on technical lead', 'Managing managers'],
    hint: 'Think about which weeks at Pinhous felt best, and why.',
    followUps: [
      'What would a company have to offer to make you pick the other one?',
      'What is the least amount of code you could write in a week and still be happy?',
    ],
    why: 'His preferred career track, and how much hands-on building he needs.',
  },
  {
    id: 'career-006',
    topic: 'career',
    type: 'open',
    depth: 2,
    prompt:
      'Describe the team you do your best work in. Not the perks: the people, and how they behave on an ordinary Wednesday afternoon.',
    hint: 'Think back to the stretches at ARO, Pinhous, Create Club or Eddy when you were most in flow.',
    followUps: [
      'What is one behaviour that would make you quietly start looking elsewhere?',
      'How does that team handle someone being wrong in public?',
    ],
    why: 'The culture and team dynamics he thrives in, which the clone uses to judge fit.',
  },
  {
    id: 'career-007',
    topic: 'career',
    type: 'scale',
    depth: 1,
    prompt: 'What size of company brings out your best work?',
    scale: { min: 1, max: 5, minLabel: 'Five people in a room', maxLabel: 'Thousands, with real process' },
    hint: 'You have seen a small studio, a startup with a 12-person dev team, and a hardware company with a 150,000-device fleet.',
    followUps: [
      'What do you lose at the size you picked?',
      'Does the answer change if AI is the core product rather than a side bet?',
    ],
    why: 'His preferred company size, a hard input when the clone assesses a role.',
  },
  {
    id: 'career-008',
    topic: 'career',
    type: 'open',
    depth: 3,
    prompt: 'What are your real dealbreakers, the things that would make you turn down an otherwise great offer?',
    hint: 'Things you have learned the hard way, not things that sound good in an interview.',
    followUps: ['Which one did you learn from a specific experience?', 'Have you ever compromised on one and regretted it?'],
    why: 'The hard constraints the clone should apply when assessing role fit.',
  },
  {
    id: 'career-009',
    topic: 'career',
    type: 'open',
    depth: 2,
    prompt: 'If a recruiter asks about compensation on a first call, how do you actually answer?',
    hint: 'The philosophy you would say out loud, not a number.',
    followUps: [
      'After co-founding a studio, how do you weigh equity against salary?',
      'What would you trade salary for, and what would you never trade it for?',
    ],
    why: 'His public-facing compensation philosophy, so the clone can answer without inventing numbers.',
  },
  {
    id: 'career-010',
    topic: 'career',
    type: 'scenario',
    depth: 2,
    prompt:
      "You've got 60 seconds in an elevator with a hiring manager who has read your resume but never met you. What do you want them to understand about you that the resume can't show?",
    hint: 'Imagine they have read every bullet and still do not get it.',
    followUps: [
      'What do people usually get wrong about you from the resume alone?',
      'How would you prove it in your first two weeks?',
    ],
    why: 'The self-pitch he most wants the clone to carry to hiring managers.',
  },
  {
    id: 'career-011',
    topic: 'career',
    type: 'scenario',
    depth: 3,
    prompt:
      "Two offers land the same week: a well-funded 30-person AI startup offering 20% more cash for a vague role ('you'll figure it out'), and a steady company offering similar pay for full ownership of their GenAI platform with a clear mandate. You have 72 hours. How do you decide?",
    hint: 'Say what you would ask each of them before deciding.',
    followUps: [
      'What single question would you ask the startup CTO?',
      'What would flip your answer?',
      'How much does the team you would work with outweigh the role itself?',
    ],
    why: 'How he evaluates a job offer in practice, and which factors actually dominate.',
  },
  {
    id: 'career-012',
    topic: 'career',
    type: 'scenario',
    depth: 2,
    prompt:
      'Your old site offered a one-week pilot project to any company you were serious about joining. A company you like accepts and hands you a vague brief on Monday. What do you build by Friday, and how do you make the week tell both sides something real?',
    hint: 'Start with what you would ask in the first 30-minute call.',
    followUps: [
      'Would you still make that offer today, as a Lead?',
      'What does a pilot week reveal about a company that interviews never do?',
    ],
    why: 'How he proves value through real work and evaluates a company from the inside.',
  },
  {
    id: 'career-013',
    topic: 'career',
    type: 'story',
    depth: 2,
    prompt: "Tell me about a moment at work when you thought 'this is exactly what I should be doing'.",
    hint: "Situation · what you were doing · what happened · what you'd want more of.",
    followUps: [
      'What specifically made it: the problem, the people, or the stakes?',
      'How do you shape a role so that happens more often?',
    ],
    why: 'The kind of work that energises him most, a strong signal for which roles fit.',
  },
  {
    id: 'career-014',
    topic: 'career',
    type: 'scale',
    depth: 3,
    prompt: 'How likely is it that you start another company in the next five years?',
    scale: { min: 1, max: 5, minLabel: 'Very unlikely', maxLabel: 'Already sketching it' },
    hint: 'Create Club taught you something about this, either way.',
    followUps: [
      'What would the company have to be about?',
      'What would need to be true in your life to make the leap again?',
    ],
    why: 'His founder ambition, which shapes how he frames long-term roles.',
  },
  {
    id: 'career-015',
    topic: 'career',
    type: 'this-or-that',
    depth: 3,
    prompt:
      'You have a Technical Product Management certificate from BrainStation, you have held Product Lead as a title, and in 2026 your site listed both Full-Stack AI Developer and AI Product Manager. Which one are you, really?',
    options: ['Engineer who thinks in product', 'Product leader who can build'],
    hint: 'Think about which half of the work you would keep if you could only keep one.',
    followUps: [
      'In 2025 you wrote that generalists become the premium asset as AI commoditises specialists. Does that still shape the roles you go for?',
      'What would a job that fully used both halves look like?',
    ],
    why: 'Where he sits between engineering and product, and whether he sees himself as a generalist.',
  },
  {
    id: 'career-016',
    topic: 'career',
    type: 'open',
    depth: 2,
    prompt:
      'You carry what you learn in one deep dive into the next domain. If you could choose the next domain to be dropped into, what would it be?',
    hint: 'Your headline says agent orchestration. Is that it, or is there something further out?',
    followUps: [
      'What have you already done to get started on it?',
      'Who is doing the most interesting work there right now?',
    ],
    why: 'His next learning target, which signals where his career is heading.',
  },
]
