import type { Question } from './types'

export const DECISIONS: Question[] = [
  {
    id: 'decisions-001',
    topic: 'decisions',
    type: 'this-or-that',
    depth: 1,
    prompt: "When you're stuck between two reasonable options, what's your actual habit?",
    options: ['Decide fast, correct later', 'Wait for one more data point'],
    hint: 'Your real habit, not the ideal one.',
    followUps: [
      'What kind of decision makes you flip to the other side?',
      'Who do you know who decides the opposite way, and what have you learned from them?',
    ],
    why: 'His default tempo for decisions under uncertainty.',
  },
  {
    id: 'decisions-002',
    topic: 'decisions',
    type: 'rapid',
    depth: 1,
    prompt: 'When a decision is stuck, what gets you unstuck: a list, a spreadsheet, a walk, or a conversation?',
    hint: 'One word is fine.',
    followUps: [
      'If it is a conversation, who is it usually with?',
      'Has that changed now that you can think out loud with an AI?',
    ],
    why: 'His go-to tool for getting unstuck, a small but telling habit.',
  },
  {
    id: 'decisions-003',
    topic: 'decisions',
    type: 'open',
    depth: 3,
    prompt:
      "Twice now you've built something that worked and then recommended not shipping it: the Pinhous recommendations POC and the IMAP MCP server. What's the rule you're following?",
    hint: 'Try to write it as one sentence someone else could apply without you in the room.',
    followUps: [
      'What would the numbers have needed to show for you to say ship?',
      'How did the people who wanted it take the recommendation?',
      'Model prices have fallen a lot since Pinhous. Have you rerun that trade-off?',
    ],
    why: 'His explicit decision rule for killing a working prototype on cost or latency grounds.',
  },
  {
    id: 'decisions-004',
    topic: 'decisions',
    type: 'open',
    depth: 2,
    prompt: 'Think of a recent decision at Eddy that you treated as a one-way door. How did you know it was one?',
    hint: 'The tracker data model, hosting the MCP server in-process, rolling out Claude Code to the team.',
    followUps: [
      'What did you do differently because it was one-way?',
      'Which decision did you treat as reversible that turned out not to be?',
    ],
    why: 'How he sorts decisions by reversibility and scales his rigour to match.',
  },
  {
    id: 'decisions-005',
    topic: 'decisions',
    type: 'scale',
    depth: 2,
    prompt: 'When the data and your gut disagree, how often does your gut win?',
    scale: { min: 1, max: 5, minLabel: 'Never, the data wins', maxLabel: 'Usually, my gut wins' },
    hint: 'Think of the last time they disagreed and what you did.',
    followUps: ['What does your gut pick up that the data usually misses?', 'When has trusting your gut burned you?'],
    why: 'How he weighs intuition against evidence, and in which situations.',
  },
  {
    id: 'decisions-006',
    topic: 'decisions',
    type: 'story',
    depth: 2,
    prompt: 'Tell me about a time a number changed a decision you were already sure about.',
    hint: "Situation · what you believed · what the number showed · what you did · what you'd do differently.",
    followUps: [
      'How confident were you before you saw it?',
      'What number do you now want in front of you before every decision like that?',
    ],
    why: 'Whether he genuinely updates on data, and how quickly.',
  },
  {
    id: 'decisions-007',
    topic: 'decisions',
    type: 'scenario',
    depth: 3,
    prompt:
      "Your company needs an internal knowledge assistant. A vendor offers one for $40k a year that does 80% of what you'd build, while yours would take six weeks plus ongoing maintenance but fit your data exactly. The CFO wants your recommendation by Friday: what is it?",
    hint: 'Walk through the numbers and the non-numbers you would put in front of the CFO.',
    followUps: [
      'What would the vendor have to get wrong for you to change your recommendation?',
      'At Eddy you built the work tracker instead of buying one. What made that a build?',
      'How do you price your own time in a decision like this?',
    ],
    why: 'His business-level build-versus-buy reasoning, including how he values ownership and his own time.',
  },
  {
    id: 'decisions-008',
    topic: 'decisions',
    type: 'scenario',
    depth: 2,
    prompt:
      "It's Thursday. A big customer is getting false leak alerts and the field team needs a fix live by Monday. You can ship a targeted patch you're 85% confident in, or a proper fix that lands Wednesday. What do you ship, and what do you tell the customer?",
    hint: 'Say what you would do in the first hour, not just the final call.',
    followUps: [
      'What would you need to see to get from 85% to comfortable?',
      'Who do you pull in before deciding, and who do you just inform?',
    ],
    why: 'How he trades speed against certainty under real customer pressure.',
  },
  {
    id: 'decisions-009',
    topic: 'decisions',
    type: 'this-or-that',
    depth: 1,
    prompt: 'Faced with a question like "will this approach be fast enough?", what do you reach for first?',
    options: ['Build a prototype to find out', 'Research until the answer is clear'],
    hint: 'The IMAP MCP prototype is one data point. Is it typical?',
    followUps: [
      'What is the most time you have wasted prototyping something research would have answered?',
      'And the reverse?',
    ],
    why: 'Whether he learns by building or by reading before he commits.',
  },
  {
    id: 'decisions-010',
    topic: 'decisions',
    type: 'open',
    depth: 2,
    prompt:
      'Create Club started in August 2024, while Pinhous was still running. What tipped you from thinking about a studio to actually starting one?',
    hint: 'Think about the week you actually committed, and what else was on the table.',
    followUps: [
      'How did you choose who to start it with?',
      'What did you believe about running a studio that turned out to be wrong?',
      'How much risk were you really taking on?',
    ],
    why: 'His appetite for risk and ownership, and how he chooses partners.',
  },
  {
    id: 'decisions-011',
    topic: 'decisions',
    type: 'story',
    depth: 3,
    prompt:
      'Your time as a co-founder at Create Club ended in March 2026, and a month later you were leading software at Eddy. Walk me through how that decision got made.',
    hint: "Situation · what you weighed · what you decided · what you'd do differently.",
    followUps: [
      'What was the single fact that tipped it?',
      'Whose opinion did you weigh most, and why them?',
      'What would have had to be true for you to keep going?',
    ],
    why: 'How he makes big career decisions: the inputs, the timing and the tipping point.',
  },
  {
    id: 'decisions-012',
    topic: 'decisions',
    type: 'open',
    depth: 2,
    prompt:
      "Of everywhere you could have gone next, you picked a company that makes water-leak detection hardware. What did Eddy have that a shinier AI startup didn't?",
    hint: 'List what you were actually weighing, including the unglamorous stuff.',
    followUps: [
      'What did you give up by choosing it?',
      'What would have made you say no?',
      'How much did the hardware and the 150,000-device fleet factor in?',
    ],
    why: 'The real criteria behind his most recent job choice, which predict his future ones.',
  },
  {
    id: 'decisions-013',
    topic: 'decisions',
    type: 'scenario',
    depth: 3,
    prompt:
      'Three months into a project you led, you realise a much simpler approach would have delivered 90% of the value in three weeks. The team is proud of what they have built, and launch is two weeks away. Do you keep going, or change course?',
    hint: 'Say what you would tell the team on Monday morning.',
    followUps: [
      'How do you stop yourself from defending the work just because you led it?',
      'Has a version of this actually happened to you?',
    ],
    why: 'How he handles sunk cost and his own attachment to past decisions.',
  },
  {
    id: 'decisions-014',
    topic: 'decisions',
    type: 'open',
    depth: 3,
    prompt:
      "What's the hardest professional decision you've made in the last three years, and what made it hard: missing information, the people affected, or just a genuinely close call?",
    hint: 'Pick one that still sits with you a little.',
    followUps: ['Would you make the same call today?', 'How did you make peace with it?'],
    why: 'What makes a decision genuinely hard for him, and how he lives with close calls.',
  },
  {
    id: 'decisions-015',
    topic: 'decisions',
    type: 'open',
    depth: 2,
    prompt: 'Focused deep dives mean saying no to a lot of interesting things. How do you decide what not to work on?',
    hint: 'Name something tempting you said no to recently.',
    followUps: [
      "What's sitting on your someday list right now?",
      'How do you stop a side project from quietly becoming the main thing?',
    ],
    why: 'His prioritisation rules, the flip side of working in focused deep dives.',
  },
]
