import type { Question } from './types'

export const FAILURE: Question[] = [
  {
    id: 'failure-001',
    topic: 'failure',
    type: 'open',
    depth: 1,
    prompt: 'What is one habit you have today that exists only because something went wrong once?',
    hint: 'A check you always run, a question you always ask, a thing you never do on a Friday.',
    followUps: ['What was the thing that went wrong?', 'Has the habit ever been overkill?'],
    why: 'Which lessons actually changed his behaviour, not just his opinions.',
  },
  {
    id: 'failure-002',
    topic: 'failure',
    type: 'this-or-that',
    depth: 1,
    prompt: 'You realise something you shipped is broken, and nobody else has noticed yet. First instinct?',
    options: ['Tell people, then fix it', 'Fix it fast, then tell'],
    hint: 'Your gut reaction, not your policy.',
    followUps: ['Has that instinct ever cost you?', 'Does it change if a customer can already see the problem?'],
    why: 'His reflex on disclosure versus quiet repair when his own work breaks.',
  },
  {
    id: 'failure-003',
    topic: 'failure',
    type: 'scale',
    depth: 1,
    prompt: 'How hard are you on yourself after a mistake at work?',
    scale: { min: 1, max: 5, minLabel: 'Shrug and move on', maxLabel: 'Replay it for weeks' },
    hint: 'Think about the last real one, not the ideal.',
    followUps: [
      'What helps you put one down?',
      'How do you want a lead to respond when you are the one who messed up?',
    ],
    why: 'His emotional relationship with failure and what support he wants from others.',
  },
  {
    id: 'failure-004',
    topic: 'failure',
    type: 'story',
    depth: 2,
    prompt:
      'Pick one incident that kept coming back at ARO before your preventive measures cut recurring incidents by 20%. What was it, and what finally stopped it?',
    hint: 'Situation · what you changed (a runbook, a check, an alert, a process) · what happened · what you would do differently.',
    followUps: [
      'Why had nobody fixed it properly before?',
      'What did the incidents you could not prevent have in common?',
      'How did you get people to actually use the documentation you owned?',
    ],
    why: 'Whether he fixes root causes systematically rather than just firefighting.',
  },
  {
    id: 'failure-005',
    topic: 'failure',
    type: 'scenario',
    depth: 2,
    prompt:
      "It's Wednesday. On Monday you told a client a feature would take 3 days. You now realise it's closer to 3 weeks, because the API you're integrating doesn't do what its docs claim. What do you do in the next hour?",
    hint: 'Who you tell, how you tell them, and what options you bring along with the bad news.',
    followUps: [
      'When has an estimate of yours actually blown up like this? What happened?',
      'Do you pad estimates now? By how much, and do you tell people you do?',
    ],
    why: 'How he communicates slipping timelines and whether his estimation habits have changed.',
  },
  {
    id: 'failure-006',
    topic: 'failure',
    type: 'story',
    depth: 2,
    prompt: 'Tell me about a project or technology bet that died, where at least part of the cause was a call you made.',
    hint: 'Situation · the call you made · what happened · what you would do differently.',
    followUps: [
      'Were there early signs you explained away?',
      'How long did it take you to admit it, and what finally convinced you?',
      'Did any of it survive into something else?',
    ],
    why: 'Whether he can own his technical and product calls and how he weighs sunk cost.',
  },
  {
    id: 'failure-007',
    topic: 'failure',
    type: 'this-or-that',
    depth: 2,
    prompt: 'Looking back over your own mistakes, which kind shows up more often?',
    options: ['Shipped too early', 'Held on too long'],
    hint: 'Count them honestly, across jobs and side projects.',
    followUps: [
      'Give me one example of the kind you picked.',
      'Which way does your instinct lean today, and is that an overcorrection?',
    ],
    why: 'Whether his mistakes tend to skew towards rushing or towards caution.',
  },
  {
    id: 'failure-008',
    topic: 'failure',
    type: 'open',
    depth: 2,
    prompt: "What's a people or team decision you made as a lead that you'd make differently today?",
    hint: 'A hire, who you put on what, a team structure, a process you imposed.',
    followUps: [
      'What did you know at the time that should have told you?',
      'Did you ever tell the people affected that you would do it differently now?',
    ],
    why: 'How he reflects on people decisions, which are harder to undo than code.',
  },
  {
    id: 'failure-009',
    topic: 'failure',
    type: 'story',
    depth: 3,
    prompt: 'Tell me about a production incident you personally caused. Not one you fixed: one you caused.',
    hint: 'Situation · what you did (and did not do) · what happened · what you changed afterwards.',
    followUps: [
      'How did you find out: an alert, a user, a colleague?',
      'Who did you tell first, and how quickly?',
      'What guardrail exists today because of it?',
    ],
    why: 'How he owns his own mistakes and what safeguards he builds afterwards.',
  },
  {
    id: 'failure-010',
    topic: 'failure',
    type: 'open',
    depth: 3,
    prompt:
      'Your regdocs eval harness caught a real regression (hit@8 fell from 96.7% to 91.3%) and you held the release. What is a regression that got past you before you worked that way?',
    hint: 'What slipped through, how it was noticed, and how long it had been live.',
    followUps: [
      'What would have caught it, if you had had it at the time?',
      'What kind of failure would your current eval setup still miss?',
    ],
    why: 'Whether he is honest about the limits of his testing and what drove his eval-first habits.',
  },
  {
    id: 'failure-011',
    topic: 'failure',
    type: 'scenario',
    depth: 3,
    prompt:
      "You ship a change on Friday afternoon. On Monday morning you learn it has been silently misclassifying about 5% of a customer's documents all weekend, and the customer noticed before anyone on your team did. Walk me through your Monday.",
    hint: 'The order you do things in (tell, contain, fix, investigate) and who hears what from you.',
    followUps: [
      'What goes in the postmortem, and is anyone named in it?',
      'How much do you tell the customer about the cause?',
      'How do you avoid overcorrecting with process nobody will follow?',
    ],
    why: 'His ownership, communication under pressure and postmortem style when a mistake reaches a customer.',
  },
  {
    id: 'failure-012',
    topic: 'failure',
    type: 'open',
    depth: 3,
    prompt:
      'What is the most expensive lesson co-founding Create Club taught you about running a business, as opposed to building software?',
    hint: 'Pricing, clients, partnership, cash, time: pick the one that cost the most.',
    followUps: [
      'What would you do differently in the first three months if you started it again?',
      'What did it teach you about yourself as a founder versus as an employee?',
      'What do you do differently inside a company now because you once helped run one?',
    ],
    why: 'What running a studio taught him and how it shapes the way he works inside companies now.',
  },
]
