import type { Question } from './types'

export const LIFE: Question[] = [
  {
    id: 'life-001',
    topic: 'life',
    type: 'rapid',
    depth: 1,
    prompt: "What's the last song you had on repeat?",
    hint: 'Artist and track. No judgement.',
    followUps: ['Where were you when it got stuck in your head?', 'Is it typical of your taste or a total outlier?'],
    why: 'A current, specific music detail that makes the clone feel human.',
  },
  {
    id: 'life-002',
    topic: 'life',
    type: 'open',
    depth: 2,
    prompt:
      'The Music app on your site shows what you are playing on Spotify, spinning on a vinyl record. What role does music actually play in your life, at work and away from it?',
    hint: 'Genres, artists, rituals, and whether you can code to music with lyrics.',
    followUps: [
      'Do you own any actual vinyl?',
      'Which artist would you want the clone to be able to talk about properly?',
      'What music takes you straight back to Mumbai or Manchester?',
    ],
    why: 'How music fits into his days, and which artists and genres he would want to discuss.',
  },
  {
    id: 'life-003',
    topic: 'life',
    type: 'story',
    depth: 2,
    prompt:
      'You rebuilt curlycloud.dev as a Mac OS System 1 desktop from 1984, down to the Chicago font and the startup chime. Tell me the story of how that happened.',
    hint: "Situation (why you started) · what you built · what happened, including what surprised you · what you'd do differently.",
    followUps: [
      'Which tiny detail are you proudest of that nobody notices?',
      'What would you add to Curly OS next?',
      'What is it about that era of computing that appeals to you?',
    ],
    why: 'His aesthetic taste and sense of play, and how he expresses personality through what he builds.',
  },
  {
    id: 'life-004',
    topic: 'life',
    type: 'this-or-that',
    depth: 1,
    prompt: 'What kind of humour gets you every time?',
    options: ['Dry and deadpan', 'Absurd and silly'],
    hint: 'Think of the last thing that made you laugh out loud.',
    followUps: [
      'Who is the funniest person you know, and what makes them funny?',
      "What's a joke or meme you've been sending everyone lately?",
    ],
    why: 'His sense of humour, so the clone can be playful in the right register.',
  },
  {
    id: 'life-005',
    topic: 'life',
    type: 'open',
    depth: 3,
    prompt: 'Mumbai, Manchester, Toronto. What did each city teach you that the other two could not have?',
    hint: 'One lesson per city, as specific as you can make it.',
    followUps: [
      'Which one do you miss in a way that surprises you?',
      'When someone asks where you are from, what do you say?',
    ],
    why: 'How each place shaped him, and what home means to him.',
  },
  {
    id: 'life-006',
    topic: 'life',
    type: 'scenario',
    depth: 1,
    prompt:
      "It's a perfect Sunday in Toronto: no work, no plans, good weather. Walk me through it from waking up to falling asleep.",
    hint: 'Times, places, food, and who is there, as much as you want to share.',
    followUps: ['Which part of that day is non-negotiable?', 'What does the January version look like?'],
    why: 'His ideal rhythm of rest, which shows what he values outside work.',
  },
  {
    id: 'life-007',
    topic: 'life',
    type: 'rapid',
    depth: 1,
    prompt: 'Your old site footer confessed "I love strawberry matcha". What else is on your regular order?',
    hint: 'Coffee shop order, comfort food, the dish you cook best.',
    followUps: ['Where in Toronto do you go for it?', 'What food from Mumbai do you still hunt for here?'],
    why: 'Specific food tastes that make the clone warm and recognisably him.',
  },
  {
    id: 'life-008',
    topic: 'life',
    type: 'story',
    depth: 3,
    prompt:
      "Your World Map app counts 24 countries, from Egypt and Japan to Mauritius and New Zealand. Tell me about the trip that changed how you think, not just what you've seen.",
    hint: 'Situation (where you were) · what you did · what happened · what changed in you afterwards.',
    followUps: ['What is the next country on the list, and why that one?', 'Planner or wanderer when you travel?'],
    why: 'What travel means to him, and the experiences that shaped his worldview.',
  },
  {
    id: 'life-009',
    topic: 'life',
    type: 'scale',
    depth: 2,
    prompt: 'When you are running on empty, how do you recharge?',
    scale: { min: 1, max: 5, minLabel: 'Alone and fully offline', maxLabel: 'Out with a crowd' },
    hint: 'Think about the weekend after a big launch.',
    followUps: [
      'What does a genuinely offline day look like for you?',
      'How do you notice you are running low before you crash?',
    ],
    why: 'Whether he recharges alone or socially, and his early warning signs of burnout.',
  },
  {
    id: 'life-010',
    topic: 'life',
    type: 'open',
    depth: 2,
    prompt: 'What do you do that has nothing to do with software, and that you would keep doing even if nobody ever knew?',
    hint: 'A sport, making things with your hands, a game, a skill you are slowly getting better at.',
    followUps: ['How did you get into it?', 'What would you do with a free month to go deep on it?'],
    why: 'His non-work interests, and whether he brings the same deep-dive intensity to them.',
  },
  {
    id: 'life-011',
    topic: 'life',
    type: 'open',
    depth: 2,
    prompt: 'What book, podcast or piece of writing genuinely changed how you think or work?',
    hint: 'Not the one you would recommend to look smart. The one that actually changed something.',
    followUps: [
      'What are you reading or listening to right now?',
      'What do you read or watch that would surprise people who only know your resume?',
    ],
    why: 'His intellectual influences and current inputs, which the clone can reference.',
  },
  {
    id: 'life-012',
    topic: 'life',
    type: 'scenario',
    depth: 2,
    prompt:
      'A friend is visiting Toronto for the first time and gives you one day to make them fall in love with the city. Where do you take them, in order?',
    hint: 'Neighbourhoods, food stops, a view, a walk. Be specific.',
    followUps: [
      'What would you deliberately skip, even though every guide recommends it?',
      'What does Toronto still not get right, in your view?',
    ],
    why: 'His relationship with Toronto, and the specific places he loves.',
  },
  {
    id: 'life-013',
    topic: 'life',
    type: 'this-or-that',
    depth: 3,
    prompt:
      'You wrote that the magic is in the bridge between digital products and real-life experiences, and you co-built an IRL puzzle game with ARK. Off the clock, which world gets more of you?',
    options: ['Screens and building things', 'Out in the physical world'],
    hint: 'Count an honest week, not an ideal one.',
    followUps: [
      'Are you happy with that split?',
      'What physical-world thing do you want more of in your life?',
      'What did watching teams run through ARK puzzles teach you about people?',
    ],
    why: 'The balance between his digital and physical life, a theme he writes about publicly.',
  },
  {
    id: 'life-014',
    topic: 'life',
    type: 'open',
    depth: 3,
    prompt: 'What do your friends come to you for? Not at work, just in life.',
    hint: 'Advice, fixing things, plans, honest opinions, restaurant picks?',
    followUps: ['What do you go to them for?', 'What do they tease you about?'],
    why: 'How the people who know him best see him, which sets the warmth and tone of the clone.',
  },
  {
    id: 'life-015',
    topic: 'life',
    type: 'story',
    depth: 2,
    prompt: 'Why Open Invite? What made you want to help host small, open-to-everyone events in Toronto?',
    hint: 'The situation where it clicked, what you did, how the first event went, what you would do differently.',
    followUps: ['What did the Cake Picnic teach you about getting strangers to talk?', 'What would you never compromise on as a host?'],
    why: 'The community side of Raj in his own words, so the clone can talk about Open Invite beyond the resume line.',
  },
  {
    id: 'life-016',
    topic: 'life',
    type: 'story',
    depth: 2,
    prompt: 'Tell me about one moment at an Open Invite event that made the work worth it.',
    hint: 'The situation, what you did, what happened, and what it changed for you.',
    followUps: ['What did you change for the next event because of it?'],
    why: 'A concrete, warm story the clone can tell when someone asks what he does outside work.',
  },
  {
    id: 'life-017',
    topic: 'life',
    type: 'this-or-that',
    depth: 1,
    prompt: 'Hosting an event or building the site for it?',
    options: ['Hosting the event', 'Building the site'],
    hint: 'Which one do you look forward to more, and why?',
    why: 'How he balances being with people and building for them.',
  },
]
