import type { Question } from './types'

export const LIGHTNING: Question[] = [
  {
    id: 'lightning-001',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Coffee order?',
    why: 'A small personal detail that makes the clone sound like a person.',
  },
  {
    id: 'lightning-002',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Favourite boring technology?',
    why: 'Which proven tools he trusts, and how much he values stability over novelty.',
  },
  {
    id: 'lightning-003',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'An AI capability you think is closer than most people expect?',
    why: 'Where he is more optimistic than the crowd, to balance what he thinks is overhyped.',
  },
  {
    id: 'lightning-004',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Best meeting length?',
    hint: 'A number of minutes.',
    why: 'How much meeting time he thinks a decision deserves.',
  },
  {
    id: 'lightning-005',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'One word teammates would use for you?',
    hint: 'Their word, not yours.',
    why: 'How he believes others see him.',
  },
  {
    id: 'lightning-006',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: "Toronto neighbourhood you'd defend?",
    why: 'His connection to the city he lives and works in.',
  },
  {
    id: 'lightning-007',
    topic: 'lightning',
    type: 'rapid',
    depth: 2,
    prompt: "One eval metric you'd keep if you could only keep one?",
    why: 'What he thinks matters most when measuring an LLM system.',
  },
  {
    id: 'lightning-008',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Slack or email for bad news?',
    why: 'How he prefers to deliver bad news, and whether he reaches for writing or a conversation.',
  },
  {
    id: 'lightning-009',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'First thing you check when a deploy goes red?',
    hint: 'The literal first tab you open.',
    why: 'His debugging instinct under pressure.',
  },
  {
    id: 'lightning-010',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Tabs or spaces, and do you actually care?',
    why: 'Whether he spends energy on style wars or hands them to a formatter and moves on.',
  },
  {
    id: 'lightning-011',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Claude Code or Copilot, if you could only keep one?',
    why: 'Which AI coding workflow he actually relies on.',
  },
  {
    id: 'lightning-012',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'A rule you break on purpose?',
    why: 'Which conventions he deliberately ignores, and how independent he is.',
  },
  {
    id: 'lightning-013',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Ideal team size?',
    why: 'The team shape he thinks works best.',
  },
  {
    id: 'lightning-014',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Rewrite or refactor, as a default?',
    why: 'His instinct when facing messy legacy code.',
  },
  {
    id: 'lightning-015',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Last thing you learned just for fun?',
    why: 'His curiosity outside of work.',
  },
  {
    id: 'lightning-016',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: "Your first question when a client says 'we need an AI agent'?",
    why: 'How he scopes AI requests, and whether he starts from the problem or the tool.',
  },
  {
    id: 'lightning-017',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Standups: keep or kill?',
    why: 'His view on team rituals and what earns a daily meeting.',
  },
  {
    id: 'lightning-018',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Nuclear engineering fact you still bring up at parties?',
    why: 'What stuck from his nuclear engineering degree, and his sense of humour.',
  },
  {
    id: 'lightning-019',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Print statements or a debugger?',
    why: 'How he actually debugs, day to day.',
  },
  {
    id: 'lightning-020',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: "Ship it or polish it, when you're unsure?",
    why: 'His default bias between speed and quality.',
  },
  {
    id: 'lightning-021',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'An AI tool you tried and dropped?',
    why: 'Which AI tools failed his bar, and what that says about his standards.',
  },
  {
    id: 'lightning-022',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'One thing Mumbai has that Toronto should steal?',
    why: 'A personal connection to Mumbai, where he worked remotely for Duit.',
  },
  {
    id: 'lightning-023',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Most dangerous words in a standup?',
    why: 'Which warning signs he has learned to hear in status updates.',
  },
  {
    id: 'lightning-024',
    topic: 'lightning',
    type: 'rapid',
    depth: 2,
    prompt: "'No' or 'I don't know': which is harder for you to say?",
    why: 'Which admission he finds harder, and so where his blind spots may be.',
  },
  {
    id: 'lightning-025',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Book you recommend most often?',
    why: 'An influence on his thinking that he returns to.',
  },
  {
    id: 'lightning-026',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Most underrated skill in an engineer?',
    why: 'What he values in engineers beyond raw technical ability.',
  },
  {
    id: 'lightning-027',
    topic: 'lightning',
    type: 'rapid',
    depth: 1,
    prompt: 'Browser tabs open right now, roughly?',
    why: 'A playful read on how he works during a deep dive.',
  },
  {
    id: 'lightning-028',
    topic: 'lightning',
    type: 'rapid',
    depth: 2,
    prompt: 'One word you want in your next performance review?',
    why: 'What he is actively trying to be known for.',
  },
]
