import type { Question } from './types'

export const WORK_STYLE: Question[] = [
  {
    id: 'work-style-001',
    topic: 'work-style',
    type: 'this-or-that',
    depth: 1,
    prompt: 'When does your best thinking happen?',
    options: ['Early morning', 'Late at night'],
    hint: 'When did you last write something you were proud of?',
    followUps: [
      'What does your ideal workday look like, hour by hour?',
      'How do you protect those hours when the rest of the team keeps different ones?',
    ],
    why: 'His energy rhythm and when he does his deepest work.',
  },
  {
    id: 'work-style-002',
    topic: 'work-style',
    type: 'this-or-that',
    depth: 1,
    prompt:
      'You worked remotely from Mumbai at Duit. If you had to pick one setup for the next three years, which would it be?',
    options: ['Fully remote', 'In the office most days'],
    hint: 'Pick one even if the honest answer is hybrid; the why is where the nuance goes.',
    followUps: [
      'What does remote work get wrong that people rarely admit?',
      'What would a good hybrid week look like for you, day by day?',
    ],
    why: 'His real preference on location and what he thinks each setup costs.',
  },
  {
    id: 'work-style-003',
    topic: 'work-style',
    type: 'open',
    depth: 1,
    prompt: 'If you could impose one rule on every meeting at your company, what would it be?',
    hint: 'A rule you would actually enforce, not a slogan.',
    followUps: [
      'Which recurring meeting would you kill first?',
      'What should always be a written doc instead of a meeting?',
    ],
    why: 'His meeting philosophy and how he wants collaboration to run.',
  },
  {
    id: 'work-style-004',
    topic: 'work-style',
    type: 'scale',
    depth: 1,
    prompt: 'How async do you want your team to be?',
    scale: { min: 1, max: 5, minLabel: 'Talk it through live', maxLabel: 'Write it down, reply later' },
    hint: 'Think about a normal week, not a crisis.',
    followUps: [
      'What should never be handled async?',
      'How long is too long to wait for a reply to a message?',
    ],
    why: 'His default communication mode and what he expects from teammates.',
  },
  {
    id: 'work-style-005',
    topic: 'work-style',
    type: 'open',
    depth: 2,
    prompt: "It's Monday morning. How do you plan the week ahead?",
    hint: 'When you do it, where the plan lives, and how much of it usually survives to Friday.',
    followUps: [
      'What always gets bumped first?',
      'How do you balance your own deep work against unblocking the team?',
    ],
    why: 'How he organizes his time and protects focus while leading.',
  },
  {
    id: 'work-style-006',
    topic: 'work-style',
    type: 'scale',
    depth: 2,
    prompt: 'What pace do you do your best work at?',
    scale: { min: 1, max: 5, minLabel: 'Steady, every single day', maxLabel: 'Intense sprints, then recover' },
    hint: 'Think about the last three months, not your best week.',
    followUps: [
      'How long can you sustain a sprint before quality slips?',
      'How do you work with teammates whose pace is the opposite of yours?',
      'One-week sprints, two-week sprints or none at all: what has worked best for your teams?',
    ],
    why: 'His natural work rhythm and how it fits a team cadence.',
  },
  {
    id: 'work-style-007',
    topic: 'work-style',
    type: 'this-or-that',
    depth: 2,
    prompt: 'Starting a new project, which would you rather be handed?',
    options: ['A problem and a deadline', 'A clear spec and a plan'],
    hint: 'Think of the project where you did your best work.',
    followUps: [
      'When has too much freedom hurt you?',
      'What is the minimum structure you want even when you have a free hand?',
    ],
    why: 'How much structure he needs to do his best work.',
  },
  {
    id: 'work-style-008',
    topic: 'work-style',
    type: 'open',
    depth: 2,
    prompt:
      'You built the Eddy team an app to record its engineering decisions. What does your own system for notes and decisions look like day to day?',
    hint: 'Tools, format, and where a decision from three months ago would be found.',
    followUps: [
      'What makes a decision worth writing down?',
      'What happens to your notes after a meeting?',
      'Which tool on your desk would be hardest to give up?',
    ],
    why: 'How he documents his thinking and whether others can find the reasoning behind his calls.',
  },
  {
    id: 'work-style-009',
    topic: 'work-style',
    type: 'story',
    depth: 2,
    prompt:
      'Tell me about the most energizing stretch of work you have had in the last few years, the kind where you lost track of time.',
    hint: 'Situation · what you were doing · what made it work · how you would recreate it.',
    followUps: [
      'What was missing from it: meetings, interruptions, something else?',
      'Now the opposite: what was in the most draining stretch you have had?',
    ],
    why: 'What energizes and drains him, so the clone can describe the environments where he thrives.',
  },
  {
    id: 'work-style-010',
    topic: 'work-style',
    type: 'scenario',
    depth: 2,
    prompt:
      "It's Tuesday, the one day this week you blocked for deep work on a gnarly retrieval bug. At 8:45am your manager adds you to an all-day planning workshop starting at 10. What do you do?",
    hint: 'Your actual reply to the invite, and what happens to the bug.',
    followUps: [
      'What would make you decline outright?',
      'How would you want a manager to handle it instead?',
      'If you go, how do you get the deep-work day back?',
    ],
    why: 'How he protects focus time and negotiates with his manager.',
  },
  {
    id: 'work-style-011',
    topic: 'work-style',
    type: 'scenario',
    depth: 2,
    prompt:
      "Monday is your first day at a new company. There's no onboarding doc, your manager is travelling all week, and the only thing on your calendar is the team standup. How do you spend the week?",
    hint: 'Day by day: who you talk to, what you read, and what you try to ship by Friday.',
    followUps: [
      'What do you want to have written down by Friday, and for whom?',
      'What would a great first week have looked like, if someone had planned it for you?',
      'How did your first weeks at Eddy actually go?',
    ],
    why: 'How he ramps up in a new environment when nobody is steering, and how self-directed he is.',
  },
  {
    id: 'work-style-012',
    topic: 'work-style',
    type: 'open',
    depth: 2,
    prompt: "How do you want to be told your work isn't good enough?",
    hint: 'Channel, timing, how blunt, and what you need to hear alongside it.',
    followUps: [
      'Who gave you feedback in exactly the right way, and what did they do?',
      'What delivery makes you shut down?',
    ],
    why: 'How to give him feedback that lands.',
  },
  {
    id: 'work-style-013',
    topic: 'work-style',
    type: 'story',
    depth: 3,
    prompt:
      'You describe how you work as focused deep dives: one problem, a few weeks, all the way to the bottom, then ship. Tell me about your most recent one, start to finish.',
    hint: 'Situation (the problem) · how you went deep · what you shipped · what you carried into the next thing.',
    followUps: [
      'What does day three of a deep dive look like: tabs, notes, what you stop doing?',
      'How do you know a deep dive is done, and not just stalled?',
      'How do you go that deep and still stay useful to a team that needs you?',
    ],
    why: 'What his signature working mode looks like in practice, and what it gives and costs a team.',
  },
  {
    id: 'work-style-014',
    topic: 'work-style',
    type: 'open',
    depth: 3,
    prompt: 'Write the three-line job description for your ideal manager.',
    hint: 'Three lines of concrete behaviour, no adjectives like "supportive".',
    followUps: [
      'What has a manager done that made you want to leave?',
      'How do you manage up when your manager does not fit that description?',
    ],
    why: 'What he needs from a manager and what drives him away.',
  },
  {
    id: 'work-style-015',
    topic: 'work-style',
    type: 'scenario',
    depth: 3,
    prompt:
      "It's 2:07am and you're on call. A page says ingestion from the device fleet has stopped: the queue is backing up, and the dashboards customers rely on will be stale by morning. You didn't write the service, and its runbook is a year old. Walk me through the first 30 minutes.",
    hint: 'Minute by minute: what you open first, what you check, and who you wake up and when.',
    followUps: [
      'What is your threshold for waking someone else up?',
      'What do you do at 10am the next day, after some sleep?',
      'What would you change so the next 2am page is shorter?',
    ],
    why: 'His incident instincts, calm under pressure and judgement about when to escalate.',
  },
]
